# Build stage
FROM node:latest as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/
RUN npm run build

# Run stage
FROM nginx:alpine
COPY --from=build-stage /app/dist/file-upload/browser /usr/share/nginx/html
# Expose port 80
EXPOSE 80